plugins {
    id 'java-library'
}

dependencies {
    api project(':usecase')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'tools.jackson.core:jackson-databind'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
