package dev.jagt.orchestrator.adapter.agent;

import dev.jagt.orchestrator.port.AgentWorktree;
import dev.jagt.orchestrator.config.OrchestratorPaths;
import dev.jagt.orchestrator.config.OrchestratorProperties;
import dev.jagt.orchestrator.adapter.Executables;
import dev.jagt.orchestrator.port.StartupCheck;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Codex reads {@code AGENTS.md} natively, so there is no alias to create. {@code $CODEX_HOME} points at a
 * jagt-owned directory inside the worktree, so the human's {@code ~/.codex} is neither read nor modified — and
 * their other MCP servers are not inherited either. Not the worktree's own {@code .codex/}: Codex reads a
 * project config layer from there, so a repository may ship one, and writing over a tracked file is a change.
 */
@Component
@ConditionalOnProperty(name = "orchestrator.agent.cli", havingValue = "codex")
@RequiredArgsConstructor
public class CodexAgentRuntime extends AbstractAgentRuntime implements StartupCheck {

    private static final String CODEX_HOME_DIR = ".jagt/codex";

    private final OrchestratorProperties properties;
    private final CodexProperties codex;
    private final OrchestratorPaths paths;

    @Override
    public List<String> problems() {
        List<String> problems = new ArrayList<>();
        Path bridge = paths.root().resolve("mcp_client.js");
        if (!Files.isRegularFile(bridge)) {
            problems.add("orchestrator.agent.cli=codex needs " + bridge + ", which is not there — the agent"
                    + " reaches jagt through it.");
        }
        if (!Executables.onPath("node")) {
            problems.add("orchestrator.agent.cli=codex needs node on PATH — it spawns the bridge itself.");
        }
        return problems;
    }

    @Override
    public String displayName() {
        return "Codex";
    }

    @Override
    public String launchCommand(Path worktree, boolean planMode) {
        // A read-only sandbox IS plan mode here: the agent can reason but cannot touch the files.
        return "CODEX_HOME=" + shellQuote(worktree.resolve(CODEX_HOME_DIR).toString()) + " " + codex.command()
                + (planMode ? " --sandbox read-only" : "")
                + " " + shellQuote(properties.agentPrompt());
    }

    @Override
    protected void wireAgent(AgentWorktree worktree) {
        // Codex's config has no verified remote-server form with custom headers, and the header is what tells
        // the backend which task is calling — hence the stdio bridge, and with it Node.
        linkStdioProxy(worktree);
        write(worktree.path().resolve(CODEX_HOME_DIR).resolve("config.toml"), configToml(worktree.path()));
    }

    /**
     * {@code approval_policy = "never"}: nobody sits in the tmux window to approve a command, so an asking agent
     * is a frozen agent. {@code workspace-write}: the worktree is the agent's sandbox, nothing outside it.
     */
    static String configToml(Path worktree) {
        return """
                # Generated by jagt for this worktree; CODEX_HOME points here, so ~/.codex stays untouched.
                approval_policy = "never"
                sandbox_mode = "workspace-write"

                [mcp_servers.jagt-orchestrator]
                command = "node"
                args = ["%s"]
                """.formatted(worktree.resolve("mcp_client.js"));
    }
}
