package dev.jagt.orchestrator.adapter.agent;

import dev.jagt.orchestrator.port.AgentWorktree;
import dev.jagt.orchestrator.config.CodexProperties;
import dev.jagt.orchestrator.config.OrchestratorPaths;
import dev.jagt.orchestrator.config.OrchestratorProperties;
import dev.jagt.orchestrator.adapter.Executables;
import dev.jagt.orchestrator.port.StartupCheck;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Codex CLI runtime — the second implementation behind {@link AgentRuntime}, selected by
 * {@code orchestrator.agent=codex}. It exists to keep the seam honest: everything that differs from Claude is
 * inside this class, and the task flow did not learn a single {@code if codex}.
 *
 * <p>Codex reads {@code AGENTS.md} natively, so there is no alias to create. Its MCP servers are declared in
 * {@code config.toml} under {@code $CODEX_HOME}, which the launch command points AT THE WORKTREE — so a task's
 * agent gets exactly jagt's MCP proxy, and the human's own {@code ~/.codex} config is neither read nor
 * modified. The flip side is that the human's other MCP servers (tracker, code host) are NOT inherited in a
 * Codex worktree; jagt's own reads no longer need them (see the {@code CodeHost} seam), but a Codex agent
 * cannot post review replies by itself yet.
 */
@Component
@ConditionalOnProperty(name = "orchestrator.agent", havingValue = "codex")
@RequiredArgsConstructor
public class CodexAgentRuntime extends AbstractAgentRuntime implements StartupCheck {

    private static final String CODEX_HOME_DIR = ".codex";

    private final OrchestratorProperties properties;
    private final CodexProperties codex;
    private final OrchestratorPaths paths;

    @Override
    public List<String> problems() {
        List<String> problems = new ArrayList<>();
        Path bridge = paths.root().resolve("mcp_client.js");
        if (!Files.isRegularFile(bridge)) {
            problems.add("orchestrator.agent=codex needs " + bridge + ", which is not there — the agent"
                    + " reaches jagt through it.");
        }
        if (!Executables.onPath("node")) {
            problems.add("orchestrator.agent=codex needs node on PATH — it spawns the bridge itself.");
        }
        return problems;
    }

    @Override
    public String displayName() {
        return "Codex";
    }

    @Override
    public String launchCommand(Path worktree, boolean planMode) {
        // read-only sandbox IS plan mode for Codex: it can read and reason but cannot touch the files, so the
        // human approves the plan in the tmux window exactly as with Claude's --permission-mode plan.
        return "CODEX_HOME=" + shellQuote(worktree.resolve(CODEX_HOME_DIR).toString()) + " " + codex.command()
                + (planMode ? " --sandbox read-only" : "")
                + " " + shellQuote(properties.agentPrompt());
    }

    @Override
    protected void wireAgent(AgentWorktree worktree) {
        // Codex spawns its MCP servers; its config has no verified remote-server form with custom headers, and
        // the header is what tells the backend which task is calling. So this runtime keeps the stdio bridge
        // (and with it Node) until somebody confirms an HTTP form on a real Codex — at which point this becomes
        // the same two lines as ClaudeAgentRuntime and the link goes away. See McpEndpoint for both paths.
        linkStdioProxy(worktree);
        write(worktree.path().resolve(CODEX_HOME_DIR).resolve("config.toml"), configToml(worktree.path()));
    }

    /**
     * The generated per-worktree Codex config. {@code approval_policy = "never"} is the counterpart of Claude's
     * allow-list: nobody sits in the tmux window to approve a command, so an asking agent is a frozen agent.
     * The sandbox stays {@code workspace-write} — the worktree is the agent's sandbox, and writes outside it
     * are not part of the deal.
     */
    static String configToml(Path worktree) {
        return """
                # Generated by jagt for this worktree; CODEX_HOME points here, so ~/.codex stays untouched.
                approval_policy = "never"
                sandbox_mode = "workspace-write"

                [mcp_servers.jagt-orchestrator]
                command = "node"
                args = ["%s"]
                """.formatted(worktree.resolve("mcp_client.js"));
    }
}
